os: linux
dist: bionic
language: java
jdk:
  - openjdk11
before_install:
  - sudo add-apt-repository universe
  - sudo apt-get -q update
  - env RUNNING_AS_CI=true ./bin/install-clojure.sh
script: bin/kaocha
